---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: node-hello-world

run:
  path: node-hello-world/ci/tasks/install-dependencies