---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: "latest"

inputs:
- name: node-hello-world

run:
  path: node-hello-world/ci/tasks/install-dependencies





