groups:
- name: main
  jobs:
  - install dependencies

resources:
- name: node-hello-world
  type: git
  source:
    branch: master
    uri: https://github.com/nboda/node-hello-world.git
# - name: PWS
#   type: cf
#   source:
#     api: https://api.run.pivotal.io
#     organization: rakesh
#     username: rakesh.gopannagari@gmail.com
#     password: Rakeshred626ra@
#     skip_cert_check: true
#     space: development

jobs:
- name: install dependencies
  serial: true
  public: true
  plan:
  - get: node-hello-world
    trigger: true
  - task: run-unit-tests
    file: node-hello-world/ci/tasks/install-dependencies.yml



